apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cpp-app
  name: cpp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cpp-app
  template:
    metadata:
      labels:
        app: cpp-app
    spec:
      containers:
      - image: harbor-repo.vmware.com/build_service/cpp-app-image
        name: cpp-app
        resources: {}
status: {}
