resources:
- name: cpp-app-source
  type: git
  source:
    uri: https://github.com/poprygun/cpp-app.git
    branch: master

- name: cpp-app-image
  type: registry-image
  icon: docker
  source:
    repository: ((harbor-registry))/cpp-app-image
    username: ((harbor-username))
    password: ((harbor-password))   

jobs:
- name: build-and-push
  plan:
  - get: cpp-app-source
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: cpp-app-source
      outputs:
      - name: image
      params:
        CONTEXT: cpp-app-source
      run:
        path: build
  - put: cpp-app-image
    params:
      image: image/image.tar