resources:
- name: cpp-app-source
  type: git
  source:
    uri: https://github.com/poprygun/cpp-app.git
    branch: master

- name: cpp-app-image
  type: registry-image
  icon: docker
  source:
    repository: ((harbor-registry))/cpp-app-image
    username: ((harbor-username))
    password: ((harbor-password))

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:poprygun/cpp-app.git
    branch: master
    file: version
    username: ((repo-username))
    private_key: ((repo-private-key))

jobs:
- name: build-and-push
  plan:
  - get: version
    params: {bump: minor}
  - put: version
    params: {file: version/version}
  - task: display-version
    config:
      platform: linux
      image_resource:
        type: registry-image
        source: {repository: "busybox"}
      inputs:
      - name: version
      run:
        path: cat
        args: [version/version]      
  - get: cpp-app-source
    trigger: true
  - task: build-task-image
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: cpp-app-source
      outputs:
      - name: image
      params:
        CONTEXT: cpp-app-source
      run:
        path: build
  - put: cpp-app-image
    params:
      image: image/image.tar
      additional_tags: version/version